### PR TITLE
Update rust version to 1.70

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by Kijewski** [comment]
The READMEs still say:

> Currently, the minimum supported Rust version is 1.63.0.

**Comment by GuillaumeGomez** [comment]
Which explains why `git grep` didn't show that. ^^'

Good catch, thanks!

**Comment by GuillaumeGomez** [comment]
Fixed the README files as well. :)

**Comment by Kijewski** [comment]
As an outsider, my review is LGTM. :)

**Comment by GuillaumeGomez** [comment]
Thanks for reviewing it. In gtk-rs we tend to enforce "have at least one maintainer beyond PR's author to give their approval before merging". So sorry but we'll have to wait a bit. ;)

**Pull request merged**
