### PR TITLE
docs links updates

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Do not merge yet, but must be merged before next release

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Needs to be re-open on gtk-rs-core (on remove changes on it).

**Comment by bilelmoussaoui** [comment]
The docs links should be updated for crates here as well

**Comment by bilelmoussaoui** [comment]
it just needs a rebase & a new PR for gtk-rs-core

**Comment by bilelmoussaoui** [comment]
Should be fixed

**Pull request closed without merging**
