### PR TITLE
Update crates version for next release

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Thanks, please also do this for gtk-rs-core :)

**Comment by sdroege** [comment]
Oh no, you missed `gtk3-macros` :)

**Comment by GuillaumeGomez** [comment]
Hum no I didn't. Or do you want it to follow gtk version as well?

**Comment by sdroege** [comment]
I thought that would make sense. Then all crates that belong together have the same version.

**Comment by GuillaumeGomez** [comment]
Sure!

**Pull request merged**
