### PR TITLE
Implement Eq, PartialEq & Hash for WeakRef

### LINKED ISSUE #45: Eq / Hash / etc. for glib::object::WeakRef
Would it be a bad idea for weak references to derive Eq / Hash / PartialEq / etc.as the GTK widgets do? Currently in a situation where it would be ideal if I could store a collection of weak references in a HashSet.

### PR DESCRIPTION
**Pull request by A6GibKm**
Fixes #45.

### CODE REVIEW

**Comment by sdroege** [comment]
From the original issue from @mmstick
> Currently in a situation where it would be ideal if I could store a collection of weak references in a HashSet.

Doing this would cause chaos easily. Once the objects are all gone, all weak references would be equal (the pointer is `NULL`) and the invariants of the hashset would be broken (all items in it are different).

I think there's something to think through a bit more here.

**Comment by A6GibKm** [comment]
Would it be better by just dropping the Hash impl from the PR?

**Comment by sdroege** [comment]
`BTreeSet` with `PartialOrd`/`Ord` have the same problem. And I don't know if `PartialEq`/`Eq` are allowed to behave like this. Needs to be checked.

**Comment by GuillaumeGomez** [comment]
Needs to be re-opened on gtk-rs-core.

**Pull request closed without merging**
