### PR TITLE
Regenerate gir

### PR DESCRIPTION
**Pull request by jf2048**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Windows CI is broken apparently. The gvsbuild version is maybe invalid?

**Comment by jf2048** [comment]
It looks like the build.py script was removed from gvsbuild recently, looking into it

**Comment by jf2048** [comment]
New version changes the cli a bit and needs to get installed with pip. It runs after updating the windows vm to get a new python version but now fails with some error when building fontconfig

**Comment by sdroege** [comment]
The gvsbuild CI is broken since quite a while here, I wouldn't block this PR on it. It can be solved separately.

**Review by sdroege — APPROVED** [review]

**Comment by jf2048** [comment]
The windows CI will also eventually need to be updated on gtk-rs-core with these changes if we ever bump the versions

**Comment by sdroege** [comment]
Yeah, do you want to submit a PR for that?

**Pull request merged**
