### PR TITLE
0.14 backports

### PR DESCRIPTION
**Pull request by sdroege**
@bilelmoussaoui I'll leave gtk4 for you. Also are there any changes in gtk4 that should be backported to gtk3 at this point?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Let's maybe wait for the test before making the backport?

**Comment by sdroege** [comment]
Sure, can keep this open until then and I'll include the test here.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
Still blocked on the test

**Comment by sdroege** [comment]
@GuillaumeGomez Should we get this in and make a bugfix release for now? This is a regular problem for people using the gtk bindings and it doesn't look like anybody has the time to fix the CI for the test.

**Comment by GuillaumeGomez** [comment]
Let's go.

**Pull request merged**
