### PR TITLE
Update to bitflags 2.0

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
Why did you merge this if the CI fails? :)

**Comment by GuillaumeGomez** [comment]
Because the changes look good and it won't work until gtk-rs-core is merged and I'll forget about it in the meantime. :)

**Comment by sdroege** [comment]
Yes but we need to regenerate this with latest gir so that it actually compiles again.

**Comment by GuillaumeGomez** [comment]
Ah, my bad. Went too quickly.

**Pull request merged**
